export const SHOW_COMPETITIONS_LOADER = 'COMPETITIONS/SHOW_LOADER';
export const HIDE_COMPETITIONS_LOADER = 'COMPETITIONS/HIDE_LOADER';
export const LOAD_COMPETITIONS_SUCCESS = 'COMPETITIONS/LOAD_SUCCESS';
export const LOAD_COMPETITIONS_ERROR = 'COMPETITIONS/LOAD_ERROR';
