export const SHOW_LEAGUE_LEADERBOARD_LOADER = 'LEAGUE_LEADERBOARD/SHOW_LOADER';
export const HIDE_LEAGUE_LEADERBOARD_LOADER = 'LEAGUE_LEADERBOARD/HIDE_LOADER';
export const LOAD_LEAGUE_LEADERBOARD_SUCCESS = 'LEAGUE_LEADERBOARD/LOAD_SUCCESS';
export const LOAD_LEAGUE_LEADERBOARD_ERROR = 'LEAGUE_LEADERBOARD/LOAD_ERROR';
