export const CHANGE_CURRENT_PAGE = 'PAGINATION/CHANGE_CURRENT_PAGE';
export const CHANGE_PAGINATION_VALUE = 'PAGINATION/CHANGE_PAGINATION_VALUE';
export const CHANGE_PAGE_SIZE = 'PAGINATION/CHANGE_PAGE_SIZE';
