export const SHOW_TEAM_SQUAD_LOADER = 'TEAM_SQUAD/SHOW_LOADER';
export const HIDE_TEAM_SQUAD_LOADER = 'TEAM_SQUAD/HIDE_LOADER';
export const LOAD_TEAM_SQUAD_SUCCESS = 'TEAM_SQUAD/LOAD_SUCCESS';
export const LOAD_TEAM_SQUAD_ERROR = 'TEAM_SQUAD/LOAD_ERROR';
