export const SHOW_TEAMS_LOADER = 'TEAMS/SHOW_LOADER';
export const HIDE_TEAMS_LOADER = 'TEAMS/HIDE_LOADER';
export const LOAD_TEAMS_SUCCESS = 'TEAMS/LOAD_SUCCESS';
export const LOAD_TEAMS_ERROR = 'TEAMS/LOAD_ERROR';
