export const SHOW_TEAM_CALENDAR_LOADER = 'TEAM_CALENDAR/SHOW_LOADER';
export const HIDE_TEAM_CALENDAR_LOADER = 'TEAM_CALENDAR/HIDE_LOADER';
export const LOAD_TEAM_CALENDAR_SUCCESS = 'TEAM_CALENDAR/LOAD_SUCCESS';
export const LOAD_TEAM_CALENDAR_ERROR = 'TEAM_CALENDAR/LOAD_ERROR';
